#!/bin/bash
#SBATCH --partition=clara-job
#SBATCH --mem=100000
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=4
#SBATCH --time=24:00:00
#SBATCH --gres=gpu:v100:1

module load Python/3.7.4-GCCcore-8.3.0
module load TensorFlow/2.3.1-fosscuda-2019b-Python-3.7.4

VENV=$(mktemp -d)
python3.7 -m venv $VENV
$VENV/bin/python3 $VENV/bin/pip3 install -r requirements.txt

CLI_ARGS=$(echo "$ARGS" | base64 -d)
$VENV/bin/python3 bin/run_canids $CLI_ARGS
